name: 'Setup Backend'
description: 'Checkout code and setup Go environment'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v6
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: backend/go.mod
        cache-dependency-path: backend/go.sum
    - name: Install dependencies
      run: go mod download
      shell: bash
      working-directory: backend
